<body class="bg-light">
    
<div class="container">
  <main>

    <div class="py-5 text-center">
      <h2>Checkout form</h2>
      <p class="lead">Below is an example form built entirely with Bootstraps form controls. Each required form
         group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill"><?php echo count($this->session->cart)?></span>
        </h4>
        <ul class="list-group mb-3">
          
            <?php
            $html = "";
            $total =  0;
            foreach ($this->session->cart as $k => $v) {
                $html.= '<li class="list-group-item d-flex justify-content-between lh-sm">
                <div>
                <h6 class="my-0">'.$v["name"].'</h6>
                <small class="text-muted">Brief description</small>
                </div>
                <span class="text-muted">'.$v["price"]*$v["quantity"].'</span>
                </li>';
                $total+= $v["price"]*$v["quantity"] ;
            }
              echo $html ;
            ?>
            <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">$5</span>
           </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>$<?php echo $total ;?></strong>
          </li>
        </ul>

        <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
        <form action="" method="POST" >
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" class="form-control" name="fname" id="firstName" required placeholder="" 
              value="<?php echo $data->first_name?>" >
              <div class="invalid-feedback">
                Valid first name is .
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" class="form-control" name="lname" id="lastName" required placeholder="" 
              value="<?php echo $data->last_name?>" >
              <div class="invalid-feedback">
                Valid last name is .
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" name="email" 
              value="<?php echo $data->email?>" id="email" disabled>
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" name="add1" id="address" required placeholder="1234 Main St" >
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" name="add2" id="address2" placeholder="Apartment or suite">
            </div>
            <div class="col-12">
              <?php echo $this->tag->hiddenField(
                  [
                      "id",
                      "value" => $data->id
                  ]
              );   ?>
            </div>
            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" name="country" id="country" >
                <option value="">Choose...</option>
                <option>India</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">State</label>
              <select class="form-select" name="state" id="state" >
                <option value="">Choose...</option>
                <option>Uttar Pradesh</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Zip</label>
              <input type="text" class="form-control" name="zip" id="zip" required placeholder="" >
              <div class="invalid-feedback">
                Zip code .
              </div>
            </div>
          </div>
          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" name="orderBtn" type="submit">Place Order</button>
        </form>
        <div class="row">
        <h2 class=" col p-5 m-5 text-success border"><?php if (isset($msg)) {
            echo $msg ;
} ?></h2>
        </div>
      </div>
    </div>
    <form action="" method="post">
          <input type="submit" name="dashboard" value="Your dashboard">
    </form>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2017-2021 Company Name</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>


  
  </body>
