
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Cart</h4>
          <p class="text-muted">Cart is empty now.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><?php echo $this->tag->linkTo([
                '#',
                'Follow On Twitter',
                'class' => 'text-white']);?>
            </li>
            <li><?php echo $this->tag->linkTo([
                '#',
                'Share On Facebook',
                'class' => 'text-white']);?>
            </li>
            <li><?php echo $this->tag->linkTo([
                '#',
                'Email me',
                'class' => 'text-white']);?>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
    <?php echo $this->tag->linkTo([
                '#',
                '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" 
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                aria-hidden="true" class="me-2" viewBox="0 0 24 24">
                <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                <circle cx="12" cy="13" r="4"/></svg>
                <strong>Shop</strong>',
                'class' => 'navbar-brand d-flex align-items-center']);?>
                <button class="navbar-toggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" 
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <?php // echo $this->tag->submitButton([
                  //"<span class=>'navbar-toggler-icon'></span>",
                 // "class" => "navbar-toggle",
                 // "data-bs-toggle"=>"collapse",
                 // "data-bs-target"=>"#navbarHeader", 
                  //"aria-controls"=>"navbarHeader", 
                 // "aria-expanded"=>"false", 
                 // "aria-label"=>"Toggle navigation"
                 // ]); ?>
    </div>
  </div>
</header>