<?php include('header.phtml');?>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="index">
                <span data-feather="home"></span>
                Dashboard
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Add Product</h1>
        </div>
       

        <!-- <form class="row g-3"  enctype="multipart/form-data"> -->
        <?php echo $this->tag->form(["","class" => "row g-3" , "enctype" => "multipart/form-data"]);  ?>


  <div class="">
      <label for="name">Product Name &nbsp; &emsp;</label> 
       <?php echo $this->tag->textField(["product_name","required" => "true"]); ?>
       
      </div>
  
   <div class="">
        <label for="product_sale_price">Product sale price </label>
        <?php echo $this->tag->textField(["product_sale_price","required" => "true"]); ?>
       
    </div>

   <div class="">
        <label for="product_list_price">product_list_price</label>
        <?php echo $this->tag->textField(["product_list_price","required" => "true"]); ?>
        
    </div>
   
    <div class="">
       <p> <label for="product_sale_price">Description</label> <br> </p>
       <?php echo Phalcon\Tag::textArea(
    [
        "product_details",
        "cols" => 50,
        "rows" => 4,
    ]
);
    ?>   
    </div>


    <div class="form-group">
    <label for="fieldImageFile" class="col-sm-2 control-label">Upload your Image</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["product_image", "size" => 30, "class" => "form-control", "id" => "fieldImageFile"]) ?>
    </div>
</div>
           
              <br><br>
            <div class="col-md-3">
            <button type="submit" class="btn btn-primary" name="addButton">Add Product</button>
            </div>

            <div class="text-danger">
             <?php  if(isset($message)) echo $message ; ?>
            </div>

          </div>
        </form>
      </main>
    </div>
  </div>
