
<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" 
    data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" 
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" 
    aria-label="Search">
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a class="nav-link px-3" href="signout.php">Sign out</a>
      </div>
    </div>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="dashboard.php">
                <span data-feather="home"></span>
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file"></span>
                Orders
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="products.php">
                <span data-feather="shopping-cart"></span>
                Products
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="users"></span>
                Customers
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="bar-chart-2"></span>
                Reports
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="layers"></span>
                Integrations
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Update Product</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button>
          </div>
        </div>

        <?php echo $this->tag->form(["","class" => "row g-3" , "enctype" => "multipart/form-data"]);  ?>
          <div class="col-md-6">
            <label for="prodID" class="form-label">Product_ID</label>
            <input type="text" disabled class="form-control" id="prodID" value="<?php echo $product->product_id ?>">
          </div>
          <div class="col-md-6">
            <input type="hidden" class="form-control" name="prodID" value="<?php echo $product->product_id ?>">
          </div>
          <div class="col-md-6">
            <label for="pname" class="form-label">Product Name</label>
            <input type="text" class="form-control" id="pname" name="pname" required value="<?php echo $product->product_name; ?>">
          </div>

          <div class="col-md-6">
            <label for="list" class="form-label">Details</label>
            <input type="text" class="form-control" name="detail" required value="<?php echo $product->product_details ?>">
          </div>
          <div class="col-md-6">
            <label for="sale" class="form-label">Sales Price</label>
            <input type="text" class="form-control" id="sale" name="sale" required value="<?php echo $product->product_sale_price; ?>">
          </div>
          <div class="col-md-6">
            <label for="list" class="form-label">List Price</label>
            <input type="text" class="form-control" id="list" name="list" required value="<?php echo $product->product_list_price; ?>">
          </div>
          <div class="col-md-8">
         <img src="../../../public/images/<?php echo $product->product_image?>" height="150" width = "150" alt="">
         <br>
          <label for="fieldImageFile" class="form-label">Upload your Image</label>
            <?php echo $this->tag->fileField(["product_image", "size" => 30, "class" => "form-control" , "id" => "fieldImageFile"]) ?>
          </div>
          <div class="col-12">
            <button type="submit" class="btn btn-primary" name="submit2">Update Product</button>
          </div>
        </form>
      </main>
    </div>
  </div>


</body>