<?php include('header.phtml'); ?>
<div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <?php echo $this->tag->linkTo([
                "admin",
                "Dashboard",
                "class" => "nav-link"
                ]
              );?>           
             </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                "admin/orders",
                "Orders",
                "class" => "nav-link"
                ]
              );?>  
            </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                "admin/products",
                "Products",
                "class" => "nav-link"
                ]
              );?>  
            </li>
          </ul>
        </div> 
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>
        </div>

        <h2>Users</h2>
        <div class="table-responsive">
       <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">User id</th>
                    <th scope="col">UserName</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Status</th>
                    <th scope="col">Change Status</th>
                    <th scope="col">DELETE</th>
                  </tr>
                </thead>
                <tbody>
          
           <?php 
            foreach ($users as $k => $v){
              ?>
                  <tr>
                        <td> <?php echo $v->id  ?></td>
                        <td> <?php echo $v->user_name  ?></td>
                        <td> <?php echo $v->first_name  ?></td>
                        <td> <?php echo $v->last_name  ?></td>
                        <td> <?php echo $v->email  ?></td>
                        <td> <?php echo $v->status  ?></td>
                        <td> 
             <?php echo $this->tag->form("admin/status");
              echo  $this->tag->hiddenField(
                [
                    "chId",
                    "value" => $v->id
                ]);
                echo  $this->tag->hiddenField(
                  [
                      "status",
                      "value" => $v->status
                  ]);
              echo $this->tag->submitButton(["Change", "class" => "btn btn-primary"]);?>
              </td>
              </form>
              <td>  
              <?php echo $this->tag->form("admin/delete");
              echo  $this->tag->hiddenField(
                [
                    "delId",
                    "value" => $v->id
                ]);
                echo  $this->tag->hiddenField(
                  [
                      "action",
                      "value" => "Users"
                  ]); 
                   echo $this->tag->submitButton(
                  ["Delete", "class" => "btn btn-danger" , "id"=>"delete"]
             ); ?> </form> </td></tr> <?php          
            }
            ?>  
          </tbody>
       </table>      
      </div>


         <?php echo $this->tag->form("admin/addUser"); ?>
         <div class="form-floating">
         <?php echo $this->tag->submitButton(["Add New User", "class" => "btn btn-lg btn-primary"]); ?>
         </div>
         </form>


      </main>
    </div>
  </div>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
 <script src="http://localhost:8080/assets/js/dUser.js"></script> 

</body>


