<?php include('header.phtml'); ?>
<div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <?php echo $this->tag->linkTo([
                "admin",
                "Dashboard",
                "class" => "nav-link"
                ]
              );?>           
             </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                "admin/orders",
                "Orders",
                "class" => "nav-link"
                ]
              );?>  
            </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                "admin/products",
                "Products",
                "class" => "nav-link"
                ]
              );?>  
            </li>
          </ul>
        </div> 
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
        </div>

        <h2>Orders</h2>
        <div class="table-responsive">
       <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">Order Id</th>
                    <th scope="col">User Id</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Order Details</th>
                    <th scope="col">Address</th>
                    <th scope="col">Status</th>

                    
                  </tr>
                </thead>
                <tbody>
          
           <?php 
            foreach ($orders as $k => $v){
              ?>
                  <tr>
                        <td> <?php echo $v->order_id  ?></td>
                        <td> <?php echo $v->user_id  ?></td>
                        <td> <?php echo $v->fname  ?></td>
                        <td> <?php echo $v->lname  ?></td>
                        <td> <?php echo $v->order_detail  ?></td>
                        <td> <?php echo $v->address  ?></td>
                        <td></td>
                       
                
          <?php  }
                  ?>
          </tbody>
       </table>      
      </div>


      </main>
    </div>
  </div>
</body>